# -*- coding: utf-8 -*-
FRONT = [
('h1','摘要'),
('body','高校共享道路是行人与骑行者在同一空间内混合通行的典型场所。此类空间中的交通冲突，既来自路权的物理竞争，也来自双方在安全认知上的系统性差异。本课题以湖北工业大学主校区为实证对象，遵循“特征识别—模型构建—需求识别—策略生成”的研究路径，对高校共享道路的交通冲突机理与安全引导策略展开系统研究，并据此开发相应的视觉引导系统设计原型。'),
('body','在交通冲突特征识别方面，本研究在校园内布设12个观测点位，历时一个月采集视频数据，采用计算机视觉与人工标注相结合的方式提取冲突事件，并依据校园慢行交通情境对碰撞时间（TTC）阈值进行修正，共识别有效冲突事件294起。研究发现，冲突在时空维度上呈现明显的集聚特征：五个热点区域承载了51.7%的冲突事件，早高峰时段冲突占比达28.2%；在行为层面，注意力分散类行为与违规运动类行为合计占比69.1%，构成冲突的主要触发因素；在环境层面，道路宽度、标识完整度与视距条件对冲突发生率具有显著影响，相关系数分别为-0.72、-0.58与-0.51。'),
('body','在行为机理研究方面，本研究整合计划行为理论、合理行为理论与技术接受模型，构建包含8个潜变量、43个观测题项的理论框架，回收有效问卷232份，运用结构方程模型开展验证性因子分析、路径分析与多群组比较。结果表明，行人与骑行者遵循不同的行为决策机理：行人的决策路径为“风险感知→安全态度→行为意图”，模型对行为意图的解释力为52.3%；骑行者的决策路径为“感知易用性→知觉行为控制→行为意图”，模型解释力为44.8%。两类主体在心理机制上的差异，为差异化安全引导策略的制定提供了理论依据。'),
('body','在认知偏差与需求分析方面，本研究运用AIGC技术生成96个标准化道路场景，构建客观安全指数（OSI）与认知偏差系数（CBC）的量化对照体系，取得870个场景—评分数据点。结果显示，弯道路段的风险被显著低估，平均CBC达32.8%；建筑出入口的风险则被高估，平均CBC为-19.3%；视距条件未进入主观安全感知的显著预测模型，构成主客观认知偏差的重要来源。结合深度访谈与参与式设计工作坊，本研究形成了涵盖五个维度、23项要素的安全引导系统需求清单。'),
('body','在策略生成与验证方面，本研究经Kano模型需求分层与国内外案例策略提取，开发了以冷蓝色骑行区与暖橙色行人区为核心的色彩编码安全引导系统原型，包含地面标识系统与立面动态提示装置两个部分，形成“静态与动态”“持续与即时”的互补关系。评估结果显示，系统可用性量表得分为76.3分，骑行道服务水平提升至B级，行人对避险空间与路径安全性的主观感知得到改善。'),
('body','本研究的价值在于，将设计学的人本视角与交通工程、行为科学的研究方法相结合，揭示了安全认知偏差作为交通冲突内生驱动机制的作用路径，并将理论发现转化为可实施的视觉引导设计方案，为高校共享道路的安全治理提供了理论与实践两个层面的支撑。'),
('body','关键词：高校共享道路；交通冲突；安全认知偏差；行为决策模型；视觉引导系统；设计干预'),

('h1','Abstract'),
('body','Shared roads on university campuses are typical spaces in which pedestrians and cyclists travel within the same physical corridor. Conflicts in such spaces arise not only from competition for right of way, but also from systematic differences in how the two groups perceive safety. Taking the main campus of Hubei University of Technology as the empirical setting, this study follows a research path of "feature identification - model construction - need identification - strategy generation" to examine the mechanisms underlying traffic conflicts on campus shared roads, and to develop a corresponding visual guidance system prototype.'),
('body','For conflict feature identification, video data were collected over one month at twelve observation points. Conflict events were extracted through a combination of computer vision and manual annotation, and classified using time-to-collision (TTC) thresholds adapted to the low-speed campus context. A total of 294 valid conflict events were identified. Conflicts were strongly clustered in time and space: five hotspots accounted for 51.7% of all events, and the morning peak accounted for 28.2%. At the behavioural level, distraction-related and rule-violating movements together accounted for 69.1% of conflicts. At the environmental level, roadway width, completeness of the signage system and sight distance were significantly associated with conflict frequency, with correlation coefficients of -0.72, -0.58 and -0.51 respectively.'),
('body','For the behavioural mechanism study, the Theory of Planned Behaviour, the Theory of Reasoned Action and the Technology Acceptance Model were integrated into a framework of eight latent variables and forty-three observed items. Based on 232 valid questionnaires, confirmatory factor analysis, path analysis and multi-group comparison were conducted using structural equation modelling. The results reveal two distinct decision mechanisms: pedestrians follow a "risk perception - safety attitude - behavioural intention" path, explaining 52.3% of the variance in intention, whereas cyclists follow a "perceived ease of use - perceived behavioural control - behavioural intention" path, explaining 44.8%.'),
('body','For the analysis of cognitive bias and design needs, ninety-six standardised road scenarios were generated using AIGC techniques, and a quantitative framework pairing an Objective Safety Index (OSI) with a Cognitive Bias Coefficient (CBC) was established, yielding 870 scenario-rating data points. Risk was significantly underestimated on curved segments (mean CBC 32.8%) and overestimated at building entrances (mean CBC -19.3%). Sight distance did not enter the significant regression model for perceived safety, which represents an important source of the observed bias. Combined with in-depth interviews and participatory design workshops, a requirement list of twenty-three elements across five dimensions was derived.'),
('body','For strategy generation and validation, Kano-based requirement stratification and case-based strategy extraction informed a colour-coded guidance system prototype, using cool blue for cycling zones and warm orange for pedestrian zones, and combining a ground-level signage system with a vertical dynamic display device. Evaluation returned a System Usability Scale score of 76.3, an improvement of the cycling level of service to grade B, and improved perceived path safety among pedestrians.'),
('body','The contribution of this study lies in combining a human-centred design perspective with methods from traffic engineering and behavioural science, in identifying safety-related cognitive bias as an endogenous driver of traffic conflict, and in translating these findings into an implementable visual guidance design, thereby providing both theoretical and practical support for the safety governance of campus shared roads.'),
('body','Keywords: campus shared road; traffic conflict; safety cognitive bias; behavioural decision model; visual guidance system; design intervention'),

('h1','目录'),
('toc',None),

('h1','图目录'),
('plain','图1  本课题技术路线图'),
('plain','图2  校园共享道路12个观测点'),
('plain','图3  校园共享道路冲突事件较高的5个热点区域'),
('plain','图4  校园共享道路5个热点区域的具体交通状况'),
('plain','图5  行人行为决策模型'),
('plain','图6  骑行者行为决策模型'),
('plain','图7  基于AI生成的共享道路交通参与者第一人称视角测试场景图（部分）'),
('plain','图8  高校共享道路安全引导系统需求清单'),
('plain','图9  面向高校共享道路主要参与者的安全引导系统设计原型'),
('plain','图10  交叉口部署预警标志设计原型'),
('plain','图11  立面动态提示装置设计原型'),

('h1','表目录'),
('plain','表1  校园共享道路观测点'),
('plain','表2  面向交通冲突者的高校共享道路交通环境特征要素调研问卷内容'),
('plain','表3  行人与骑行者在校园共享道路中的TTC分级'),
('plain','表4  冲突事件空间分布统计'),
('plain','表5  冲突行为模式统计'),
('plain','表6  校园共享道路交通环境与冲突行为的相关性统计'),
('plain','表7  高校共享道路交通安全行为要素表'),
('plain','表8  高校共享道路交通安全行为研究要素及其编码'),
('plain','表9  样本人口分布特征'),
('plain','表10  直接路径系数'),
('plain','表11  多群组分析路径系数比较'),
('plain','表12  行人群体决定性因素重要性排序'),
('plain','表13  骑行者群体决定性因素重要性排序'),
('plain','表14  高校共享道路交通环境主观认知指标及其水平'),
('plain','表15  高校共享道路交通安全客观指标表'),
('plain','表16  CBC认知偏差系数表'),
('plain','表17  高校共享道路情境下不同场景类型的认知偏差统计'),
('plain','表18  客观因素对主观安全感知的回归分析结果'),
('plain','表19  面向高校共享道路参与者的安全引导系统需求清单'),
('plain','表20  基于KANO模型的高校共享道路安全引导系统需求分类统计表'),
('plain','表21  面向高校共享道路主要参与者的14项需求的安全引导策略提取统计'),
('plain','附表A-1  校园共享道路观测点位登记与环境参数实测表'),
('plain','附表B-1  校园共享道路冲突行为编码手册'),
('plain','附表C-1  交通环境特征要素调研问卷题项'),
('plain','附表C-2  安全行为量表人口统计学题项'),
('plain','附表C-3  系统可用性量表（SUS）题项'),
('plain','附表D-1  访谈资料三级编码对照表（节选）'),
('plain','附表E-1  场景正交设计表（节选）'),
('plain','附表E-2  9个研究路段客观安全指数评分明细'),
('plain','附表F-1  各研究环节专家构成'),
('plain','附表F-2  德尔菲两轮专家评分汇总'),

('h1','缩略语表'),
('table','', ['缩略语','英文全称','中文名称'], [
 ['AIGC','Artificial Intelligence Generated Content','人工智能生成内容'],
 ['AVE','Average Variance Extracted','平均方差萃取量'],
 ['BLOS','Bicycle Level of Service','自行车服务水平'],
 ['CBC','Cognitive Bias Coefficient','认知偏差系数'],
 ['CFA','Confirmatory Factor Analysis','验证性因子分析'],
 ['CFI','Comparative Fit Index','比较拟合指数'],
 ['CR','Composite Reliability','组合信度'],
 ['IPA','Importance-Performance Analysis','重要度—满意度分析'],
 ['OSI','Objective Safety Index','客观安全指数'],
 ['PBC','Perceived Behavioral Control','知觉行为控制'],
 ['PEU','Perceived Ease of Use','感知易用性'],
 ['PU','Perceived Usefulness','感知有用性'],
 ['PUCE','Path User Comfort Equivalent','路径使用者舒适度当量'],
 ['RMSEA','Root Mean Square Error of Approximation','近似误差均方根'],
 ['SEM','Structural Equation Modeling','结构方程模型'],
 ['SRMR','Standardized Root Mean Square Residual','标准化残差均方根'],
 ['SUS','System Usability Scale','系统可用性量表'],
 ['TAM','Technology Acceptance Model','技术接受模型'],
 ['TLI','Tucker-Lewis Index','塔克—刘易斯指数'],
 ['TPB','Theory of Planned Behavior','计划行为理论'],
 ['TRA','Theory of Reasoned Action','合理行为理论'],
 ['TTC','Time to Collision','碰撞时间'],
], [1400, 4400, 2696], ['center','left','left']),
]
