# -*- coding: utf-8 -*-
# 参考文献条目：仅收录可核实来源——申报书原有10条、报告方法学与理论所必需的经典文献、报告已点名的政策标准文件
REFS = {
'纲要':   '中共中央, 国务院. 教育强国建设规划纲要（2024—2035年）[Z]. 北京, 2025.',
'武办法': '武汉市人民政府. 武汉市非机动车管理办法[Z]. 武汉, 2022.',
'CJJ37':  '中华人民共和国住房和城乡建设部. 城市道路工程设计规范: CJJ 37—2012（2016年版）[S]. 北京: 中国建筑工业出版社, 2016.',
'李琳':   '李琳, 叶宇, 陈泳. 城市步行安全及其环境影响要素研究综述与展望[J]. 风景园林, 2025, 32(2): 86-94.',
'吕能超': '吕能超, 王玉刚, 周颖, 等. 道路交通安全分析与评价方法综述[J]. 中国公路学报, 2023, 36(4): 183-201.',
'刘孟歆': '刘孟歆, 秦华, 岳晨, 等. 右转车辆与过街行人交互过程的影响因素研究[J]. 包装工程, 2023, 44(12): 118-125.',
'裴玉龙': '裴玉龙, 龙钰, 马丹. 交通安全意识对非机动车骑行者危险骑行行为的影响研究[J]. 交通信息与安全, 2024, 42(1): 49-58+66.',
'张乐':   '张乐, 汤晓敏. 可供性视角下大学老校区公共空间评价与更新设计指引——以上海交通大学徐汇校区为例[J]. 中国园林, 2025, 41(5): 115-122.',
'ZhangL': 'ZHANG Z, FISHER T, WANG H. Walk Score, environmental quality and walking in a campus setting[J]. Land, 2023, 12(4): 732.',
'Chen':   'CHEN H, GUO Y, LI L. Promoting sustainable mobility on campus: uncovering the behavioral mechanisms behind non-compliant e-bike use among university students[J]. Sustainability, 2025, 17(15): 7147.',
'Miao':   'MIAO L, LIU F, DENG Y. Analysis of traffic conflicts on slow-moving shared paths in Shenzhen, China[J]. Sustainability, 2025, 17(9): 4095.',
'Kellstedt':'KELLSTEDT K, SPENGLER J O, MADDOCK J E. Comparing perceived and objective measures of bikeability on a university campus: a case study[J]. SAGE Open, 2021, 11(2): 21582440211018685.',
'Stulpnagel':'VON STÜLPNAGEL R, RINTELEN H. A matter of space and perspective: cyclists\', car drivers\' and pedestrians\' assumptions about subjective safety in shared traffic situations[J]. Transportation Research Part A: Policy and Practice, 2024, 179: 103941.',
'Ajzen':  'AJZEN I. The theory of planned behavior[J]. Organizational Behavior and Human Decision Processes, 1991, 50(2): 179-211.',
'Fishbein':'FISHBEIN M, AJZEN I. Belief, attitude, intention and behavior: an introduction to theory and research[M]. Reading, MA: Addison-Wesley, 1975.',
'Davis':  'DAVIS F D. Perceived usefulness, perceived ease of use, and user acceptance of information technology[J]. MIS Quarterly, 1989, 13(3): 319-340.',
'Venkatesh':'VENKATESH V, DAVIS F D. A theoretical extension of the technology acceptance model: four longitudinal field studies[J]. Management Science, 2000, 46(2): 186-204.',
'Hamilton':'HAMILTON-BAILLIE B. Shared space: reconciling people, places and traffic[J]. Built Environment, 2008, 34(2): 161-181.',
'Gibson': 'GIBSON J J. The ecological approach to visual perception[M]. Boston: Houghton Mifflin, 1979.',
'Peltzman':'PELTZMAN S. The effects of automobile safety regulation[J]. Journal of Political Economy, 1975, 83(4): 677-726.',
'Wilde':  'WILDE G J S. The theory of risk homeostasis: implications for safety and health[J]. Risk Analysis, 1982, 2(4): 209-225.',
'Hayward':'HAYWARD J C. Near-miss determination through use of a scale of danger[J]. Highway Research Record, 1972, 384: 24-34.',
'Hyden':  'HYDÉN C. The development of a method for traffic safety evaluation: the Swedish traffic conflicts technique[R]. Lund: Lund University, Bulletin 70, 1987.',
'Gettman':'GETTMAN D, HEAD L. Surrogate safety measures from traffic simulation models[J]. Transportation Research Record, 2003, 1840(1): 104-115.',
'Landis': 'LANDIS B W, VATTIKUTI V R, BRANNICK M T. Real-time human perceptions: toward a bicycle level of service[J]. Transportation Research Record, 1997, 1578(1): 119-126.',
'Braun':  'BRAUN V, CLARKE V. Using thematic analysis in psychology[J]. Qualitative Research in Psychology, 2006, 3(2): 77-101.',
'Strauss':'STRAUSS A, CORBIN J. Basics of qualitative research: techniques and procedures for developing grounded theory[M]. 2nd ed. Thousand Oaks: Sage, 1998.',
'Dalkey': 'DALKEY N, HELMER O. An experimental application of the Delphi method to the use of experts[J]. Management Science, 1963, 9(3): 458-467.',
'Cochran':'COCHRAN W G. Sampling techniques[M]. 3rd ed. New York: John Wiley & Sons, 1977.',
'Nunnally':'NUNNALLY J C, BERNSTEIN I H. Psychometric theory[M]. 3rd ed. New York: McGraw-Hill, 1994.',
'Fornell':'FORNELL C, LARCKER D F. Evaluating structural equation models with unobservable variables and measurement error[J]. Journal of Marketing Research, 1981, 18(1): 39-50.',
'Hu':     'HU L, BENTLER P M. Cutoff criteria for fit indexes in covariance structure analysis: conventional criteria versus new alternatives[J]. Structural Equation Modeling, 1999, 6(1): 1-55.',
'Preacher':'PREACHER K J, HAYES A F. Asymptotic and resampling strategies for assessing and comparing indirect effects in multiple mediator models[J]. Behavior Research Methods, 2008, 40(3): 879-891.',
'Cheung': 'CHEUNG G W, RENSVOLD R B. Evaluating goodness-of-fit indexes for testing measurement invariance[J]. Structural Equation Modeling, 2002, 9(2): 233-255.',
'Sweller':'SWELLER J. Cognitive load during problem solving: effects on learning[J]. Cognitive Science, 1988, 12(2): 257-285.',
'Wickens':'WICKENS C D. Multiple resources and performance prediction[J]. Theoretical Issues in Ergonomics Science, 2002, 3(2): 159-177.',
'Tversky':'TVERSKY A, KAHNEMAN D. Judgment under uncertainty: heuristics and biases[J]. Science, 1974, 185(4157): 1124-1131.',
'Slovic': 'SLOVIC P. Perception of risk[J]. Science, 1987, 236(4799): 280-285.',
'Cohen':  'COHEN J. Statistical power analysis for the behavioral sciences[M]. 2nd ed. Hillsdale, NJ: Lawrence Erlbaum, 1988.',
'Martilla':'MARTILLA J A, JAMES J C. Importance-performance analysis[J]. Journal of Marketing, 1977, 41(1): 77-79.',
'Kano':   'KANO N, SERAKU N, TAKAHASHI F, et al. Attractive quality and must-be quality[J]. Journal of the Japanese Society for Quality Control, 1984, 14(2): 39-48.',
'DoubleD':'DESIGN COUNCIL. Eleven lessons: a study of the design process[R]. London: Design Council, 2007.',
'Brooke': 'BROOKE J. SUS: a "quick and dirty" usability scale[M]//JORDAN P W, THOMAS B, WEERDMEESTER B A, et al. Usability evaluation in industry. London: Taylor & Francis, 1996: 189-194.',
'Bangor08':'BANGOR A, KORTUM P T, MILLER J T. An empirical evaluation of the System Usability Scale[J]. International Journal of Human-Computer Interaction, 2008, 24(6): 574-594.',
'Bangor09':'BANGOR A, KORTUM P, MILLER J. Determining what individual SUS scores mean: adding an adjective rating scale[J]. Journal of Usability Studies, 2009, 4(3): 114-123.',
'Norman': 'NORMAN D A. The design of everyday things[M]. Revised and expanded ed. New York: Basic Books, 2013.',
'Lynch':  'LYNCH K. The image of the city[M]. Cambridge, MA: MIT Press, 1960.',
'Thaler': 'THALER R H, SUNSTEIN C R. Nudge: improving decisions about health, wealth, and happiness[M]. New Haven: Yale University Press, 2008.',
}

REFS.update({
'PRISMA':'PAGE M J, MCKENZIE J E, BOSSUYT P M, et al. The PRISMA 2020 statement: an updated guideline for reporting systematic reviews[J]. BMJ, 2021, 372: n71.',
'Moher':'MOHER D, LIBERATI A, TETZLAFF J, et al. Preferred reporting items for systematic reviews and meta-analyses: the PRISMA statement[J]. BMJ, 2009, 339: b2535.',
'Karndacharuk':'KARNDACHARUK A, WILSON D J, DUNN R. A review of the evolution of shared (street) space concepts in urban environments[J]. Transport Reviews, 2014, 34(2): 190-220.',
'Moody':'MOODY S, MELIA S. Shared space: research, policy and problems[J]. Proceedings of the Institution of Civil Engineers - Transport, 2014, 167(6): 384-392.',
'Allen':'ALLEN B L, SHIN B T, COOPER P J. Analysis of traffic conflicts and collisions[J]. Transportation Research Record, 1978, 667: 67-74.',
'Laureshyn':'LAURESHYN A, SVENSSON A, HYDEN C. Evaluation of traffic safety, based on micro-level behavioural data: theoretical framework and first implementation[J]. Accident Analysis & Prevention, 2010, 42(6): 1637-1646.',
'Johnsson':'JOHNSSON C, LAURESHYN A, DE CEUNYNCK T. In search of surrogate safety indicators for vulnerable road users: a review of surrogate safety indicators[J]. Transport Reviews, 2018, 38(6): 765-785.',
'Zheng':'ZHENG L, ISMAIL K, MENG X. Traffic conflict techniques for road safety analysis: open questions and some insights[J]. Canadian Journal of Civil Engineering, 2014, 41(7): 633-641.',
'Cervero':'CERVERO R, KOCKELMAN K. Travel demand and the 3Ds: density, diversity, and design[J]. Transportation Research Part D: Transport and Environment, 1997, 2(3): 199-219.',
'Ewing':'EWING R, HANDY S. Measuring the unmeasurable: urban design qualities related to walkability[J]. Journal of Urban Design, 2009, 14(1): 65-84.',
'Frank':'FRANK L D, SALLIS J F, SAELENS B E, et al. The development of a walkability index: application to the Neighborhood Quality of Life Study[J]. British Journal of Sports Medicine, 2010, 44(13): 924-933.',
'Sorton':'SORTON A, WALSH T. Bicycle stress level as a tool to evaluate urban and suburban bicycle compatibility[J]. Transportation Research Record, 1994, 1438: 17-24.',
'Mekuria':'MEKURIA M C, FURTH P G, NIXON H. Low-stress bicycling and network connectivity[R]. San Jose: Mineta Transportation Institute, Report 11-19, 2012.',
'Bandura':'BANDURA A. Self-efficacy: toward a unifying theory of behavioral change[J]. Psychological Review, 1977, 84(2): 191-215.',
'Parker':'PARKER D, MANSTEAD A S R, STRADLING S G, et al. Intention to commit driving violations: an application of the theory of planned behavior[J]. Journal of Applied Psychology, 1992, 77(1): 94-101.',
'Reason':'REASON J, MANSTEAD A, STRADLING S, et al. Errors and violations on the roads: a real distinction?[J]. Ergonomics, 1990, 33(10-11): 1315-1332.',
'Rosenstock':'ROSENSTOCK I M. Historical origins of the health belief model[J]. Health Education Monographs, 1974, 2(4): 328-335.',
'Rogers':'ROGERS R W. A protection motivation theory of fear appeals and attitude change[J]. Journal of Psychology, 1975, 91(1): 93-114.',
'Venkatesh03':'VENKATESH V, MORRIS M G, DAVIS G B, et al. User acceptance of information technology: toward a unified view[J]. MIS Quarterly, 2003, 27(3): 425-478.',
'Passini':'PASSINI R. Wayfinding in architecture[M]. New York: Van Nostrand Reinhold, 1984.',
'Arthur':'ARTHUR P, PASSINI R. Wayfinding: people, signs, and architecture[M]. New York: McGraw-Hill, 1992.',
'Miller':'MILLER G A. The magical number seven, plus or minus two: some limits on our capacity for processing information[J]. Psychological Review, 1956, 63(2): 81-97.',
'Ware':'WARE C. Information visualization: perception for design[M]. 3rd ed. Waltham: Morgan Kaufmann, 2013.',
'Elliot':'ELLIOT A J, MAIER M A. Color psychology: effects of perceiving color on psychological functioning in humans[J]. Annual Review of Psychology, 2014, 65: 95-120.',
'Jeffery':'JEFFERY C R. Crime prevention through environmental design[M]. Beverly Hills: Sage, 1971.',
'Newman':'NEWMAN O. Defensible space: crime prevention through urban design[M]. New York: Macmillan, 1972.',
'NormanD':'NORMAN D A, DRAPER S W. User centered system design: new perspectives on human-computer interaction[M]. Hillsdale, NJ: Lawrence Erlbaum, 1986.',
'Sanders':'SANDERS E B N, STAPPERS P J. Co-creation and the new landscapes of design[J]. CoDesign, 2008, 4(1): 5-18.',
'Nielsen':'NIELSEN J. Usability engineering[M]. San Francisco: Morgan Kaufmann, 1993.',
'道交法':'全国人民代表大会常务委员会. 中华人民共和国道路交通安全法[Z]. 北京, 2021年修正.',
'GB17761':'国家市场监督管理总局, 国家标准化管理委员会. 电动自行车安全技术规范: GB 17761—2018[S]. 北京: 中国标准出版社, 2018.',
})

# (锚点字符串, [文献键]) —— 引注插在锚点之后；按正文出现顺序自动编号
CITES = [
 ('《教育强国建设规划纲要（2024-2035年）》将校园安全作为实现新时代教育现代化的重要目标之一', ['纲要']),
 ('实现了从原则性要求到可操作规则的制度具化', ['武办法']),
 ('针对深圳共享路径的一项研究通过部署摄像头和轨迹分析', ['Miao']),
 ('国内外研究均探讨了校园道路使用者的主观安全感受及影响因素', ['ZhangL','Kellstedt']),
 ('或路径行人舒适度指数（Path User Comfort Equivalent， PUCE ）等相关方法对校园交通环境特征进行测度', ['Landis']),
 ('与技术接受模型（Technology Acceptance Model，TAM）的理论框架', ['Ajzen','Fishbein','Davis']),
 ('有研究人员针对408名校园内的电动自行车用户开展了结构方程模型分析', ['Chen']),
 ('此外，还有研究人员从态度、主观规范、行为控制感等维度识别影响安全行为的关键心理驱动因素', ['裴玉龙']),
 ('同时，有研究人员利用AIGC工具生成的场景图片模拟行人和骑行者的交会场景', ['Stulpnagel']),
 ('研究人员基于研究结果，还通过精确操控情境变量揭示风险感知形成认知心理模型', ['刘孟歆']),
 ('可明显减少行人与车辆直接冲突的机会', ['李琳','吕能超']),
 ('共享道路（Shared Space）概念最早由荷兰交通工程师Hans Monderman提出', ['Hamilton']),
 ('但其在高密度、高流量的校园环境中的适用性仍存在争议', ['Peltzman','Wilde']),
 ('更是一个复杂的“人-环境-行为”交互系统', ['Gibson','张乐']),
 ('研究团队采用德尔菲法进行两轮专家咨询', ['Dalkey']),
 ('TTC是交通冲突技术中最经典且最常用的时间类替代安全指标', ['Hayward','Hyden','Gettman']),
 ('访谈数据方面，本研究采用主题分析法进行处理', ['Braun']),
 ('研究团队按照传统的质性分析程序实施三级编码', ['Strauss']),
 ('风险感知（Risk Perception）为68.3%', ['Slovic']),
 ('TAM虽最初应用于技术接受领域', ['Venkatesh']),
 ('依据Cochran公式', ['Cochran']),
 ('虽然整体拟合可接受，但部分指标未达到优秀标准', ['Hu']),
 ('组合信度（CR）范围为0.801-0.894', ['Nunnally']),
 ('平均方差萃取量（AVE）范围为0.512-0.687', ['Fornell']),
 ('间接效应通过Bootstrap进行检验', ['Preacher']),
 ('多群组分析用于检验模型在行人和骑行者两个群体间的差异', ['Cheung']),
 ('考虑到问卷长度限制和参与者认知负荷', ['Sweller']),
 ('第四，注意力资源分配失衡', ['Wickens']),
 ('该现象可能与“可得性启发式”有关', ['Tversky']),
 ('Cohen\'s d=0.31，效应量为中等水平', ['Cohen']),
 ('本研究采用重要度-满意度分析（Importance-Performance Analysis,IPA）', ['Martilla']),
 ('另外，Kano模型分析进一步将校园共享道路中安全引导系统的要素划分为三类需求', ['Kano']),
 ('研究方法体系的构建基于设计学的“双钻模型”（Double Diamond Model）', ['DoubleD']),
 ('通过建立“需求-功能-形式”的映射关系', ['Norman','Lynch']),
 ('当研究团队展示社会规范可视化的概念原型时', ['Thaler']),
 ('采用系统可用性量表对导视系统的主观体验进行测量', ['Brooke']),
 ('高于行业普遍认可的68分可用性阈值', ['Bangor08','Bangor09']),
 ('依据《城市道路工程设计规范》', ['CJJ37']),
]
